-- Niko Udon kitchen app — stock list update (2026-08-05)
-- Run this once in the Supabase SQL Editor on your LIVE project.
-- It only touches stock_items (from "PREP CHECKER - udon.csv" and
-- "PREP CHECKER - tempura.csv") — your checklist and menu are untouched.
-- Any closing check status staff had set for today gets cleared since the
-- whole table is replaced.

truncate table stock_items restart identity;

insert into stock_items (section, name, gf_par_wd, gf_par_we, gf_unit, bw_par_wd, bw_par_we, bw_unit, bd_par_wd, bd_par_we, bd_unit, closing_options, closing_status, note, sort_order) values
('Tempura', 'Shrimp', '2', '3', 'box', NULL, NULL, NULL, '4', '4', 'pack', 'prep/fill/unsure', '', '[!] Move the same number of frozen ones to the walk-in when using a defrosted one x4', 1),
('Tempura', 'Chicken', '4', '6', 'box', '0', '2', 'box', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 2),
('Tempura', 'Lotus Root', '2', '4', 'box', NULL, NULL, NULL, '2', '2', 'pack', 'prep/fill/unsure', '', '[!] Move the same number of frozen ones to the walk-in when using a defrosted one x2', 3),
('Tempura', 'Eggplant', '2', '4', 'box', '0', '2', 'box', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 4),
('Tempura', 'Shiso (1 box = 2 packages)', '2', '3', 'box', '4', '6', 'box', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 5),
('Tempura', 'Batter', '1', '2', 'bat', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 6),
('Tempura', 'Vegetable Kakiage', '4', '4', 'bag', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 7),
('Sushi & Sashimi Prep', 'Nori', 'half', 'full', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', 'Room temp', 8),
('Sushi & Sashimi Prep', 'Sushi Rice', '2', '3', 'box', '2', '4', 'box', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 9),
('Sushi & Sashimi Prep', 'Cut Shiso', '3', '6', 'leaves', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 10),
('Sushi & Sashimi Prep', 'Cut Cucumber', '1', '2', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 11),
('Sushi & Sashimi Prep', 'White Ginger', '0.5', '1', 'box', '1', '1', 'box', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 12),
('Sushi & Sashimi Prep', 'Fried Tofu (Inari)', '0.25', '0.5', 'box', NULL, NULL, NULL, '1', '1', 'pack', 'prep/fill/unsure', '', '[!] Move the same number of frozen ones to the walk-in when using a defrosted one x1', 13),
('Sushi & Sashimi Prep', 'Guacamole', '0.5', '1', 'bag', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 14),
('Sushi & Sashimi Prep', 'Ponzu Jelly', '0.5', '1', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 15),
('Sushi & Sashimi Prep', 'Tsuma', '0.5', '1', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 16),
('Sushi & Sashimi Prep', 'Eel', '2', '4', 'pack', NULL, NULL, NULL, '2', '4', 'pack', 'prep/fill/unsure', '', '[!] Move the same number of frozen ones to the walk-in when using a defrosted one x3', 17),
('Sushi & Sashimi Prep', 'Tuna', '1', '2', 'plate', NULL, NULL, NULL, '2', '3', 'saku', 'prep/fill/unsure', '', '* Defrost needed', 18),
('Sushi & Sashimi Prep', 'Salmon', '1', '2', 'plate', NULL, NULL, NULL, '2', '3', 'saku', 'prep/fill/unsure', '', '* Defrost needed', 19),
('Sushi & Sashimi Prep', 'Scallop', '1', '2', 'plate', NULL, NULL, NULL, '10', '15', 'pcs', 'prep/fill/unsure', '', '* Defrost needed', 20),
('Sushi & Sashimi Prep', 'Ikura', '0.5', '1', 'box', NULL, NULL, NULL, '0', '0', 'box', 'prep/fill/unsure', '', '* Defrost needed', 21),
('Sushi & Sashimi Prep', 'Wasabi', '0.5', '1', 'bag', NULL, NULL, NULL, '1', '2', 'bag', 'prep/fill/unsure', '', '* Defrost needed', 22),
('Cold Vegetables', 'Oyster', '0.5', '1', 'box', '1', '2', 'box', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 23),
('Cold Vegetables', 'Opened Oyster', '6', '12', 'pcs', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 24),
('Cold Vegetables', 'Oyster Mixed Ponzu', '1', '1', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 25),
('Cold Vegetables', 'Salad Leaf', '1', '1', 'bat', '1', '2', 'box', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 26),
('Cold Vegetables', 'Cut Cucumber', '1', '2', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 27),
('Cold Vegetables', 'Radish', '1', '2', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 28),
('Cold Vegetables', 'Cauliflower', '1', '1', 'bat', '2', '4', 'box', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 29),
('Cold Vegetables', 'Cut Lemon', '12', '24', 'pcs', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 30),
('Cold Vegetables', 'Sliced Lemon', '6', '12', 'pcs', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 31),
('Cold Vegetables', 'Fish Tartare', '1', '2', 'bag', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 32),
('Cold Vegetables', 'Orange Zest', '1', '1', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 33),
('Cold Vegetables', 'Daikon Cress', '1', '1.5', 'pack', '2', '3', 'pack', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 34),
('Cold Vegetables', 'Pink Ginger', '0.5', '1', 'bat', '1', '1', 'bat', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 35),
('Cold Vegetables', 'Grated Ginger', '1', '1', 'bat', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 36),
('Cold Vegetables', 'Grated White Radish', '2', '2', 'bat', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 37),
('Cold Vegetables', 'Wakame', '2', '2', 'bat', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 38),
('Cold Vegetables', 'Onion', '2', '2', 'bat', '2', '4', 'bat', NULL, NULL, NULL, 'prep/fill/unsure', '', '[!] Move the same number of frozen ones to the walk-in when using a defrosted one x1', 39),
('Cold Vegetables', 'Udon Crisp', '0.5', '1', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', 'Room temp', 40),
('Cold Vegetables', 'Egg', '1', '1', 'bat', '1', '1', 'bat', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 41),
('Cold Vegetables', 'Edamame', '4', '6', 'bag', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 42),
('Main Udon', 'Txuleton', NULL, NULL, 'pcs', NULL, NULL, 'pcs', NULL, NULL, 'pcs', 'prep/fill/unsure', '', 'Need to order 1 day before', 43),
('Main Udon', 'Entrecote', '4', '8', 'portion', '4', '6', 'pack', NULL, NULL, NULL, 'prep/fill/unsure', '', '* Defrost needed', 44),
('Main Udon', 'Watercress', '1', '2', 'bag', '1', '2', 'bag', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 45),
('Main Udon', 'Tuna Katsu', '4', '8', 'pcs', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 46),
('Main Udon', 'Duck', '1', '1.5', 'bat', '1', '2', 'bag (3-4 pcs in bag)', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 47),
('Main Udon', 'Duck & Leek', '1', '1', 'box', '1', '2', 'bag', NULL, NULL, 'bag', 'prep/fill/unsure', '', NULL, 48),
('Main Udon', 'Shigure', '1', '1', 'bat', '1', '2', 'bat', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 49),
('Main Udon', 'Chashu', '1', '2', 'bat', '1', '2', 'box', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 50),
('Main Udon', 'Kitsune', '1', '1', 'bat', NULL, NULL, NULL, '1', '2', 'bag', 'prep/fill/unsure', '', '[!] Move the same number of frozen ones to the walk-in when using a defrosted one x1', 51),
('Main Udon', 'Udon Soup', '2', '2', 'bat', '2', '4', 'bat', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 52),
('Main Udon', 'Okinawa Soup', '1', '1', 'bat', '1', '2', 'container', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 53),
('Main Udon', 'Vegan Soup', '1', '1', 'bat', '1', '2', 'bat', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 54),
('Main Udon', 'BK Soup', '1', '1', 'bat', '1', '2', 'bat', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 55),
('Main Udon', 'BK Vegan Soup', '0.25', '0.5', 'bottle', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 56),
('Desserts', 'Crème Brûlée', '6', '6', 'pcs', '6', '12', 'pcs', NULL, NULL, NULL, 'prep/fill/unsure', '', '* Defrost needed', 57),
('Desserts', 'Mochi Ice Cream', '1', '2', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 58),
('Desserts', 'Sesame Kinako', '0.25', '0.5', 'box', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 59),
('Desserts', 'Whipped Cream', '1', '1', NULL, '1', '1', NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 60),
('Sauces & Condiments', 'Vegan Ponzu', '0.5', '1', 'bottle', '1', '1', 'bottle', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 61),
('Sauces & Condiments', 'Nikiri', '0.5', '1', 'bottle', '1', '2', 'bottle', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 62),
('Sauces & Condiments', 'Dontare', '0.5', '1', 'bottle', '1', '2', 'bottle', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 63),
('Sauces & Condiments', 'Tuna Tamari', '0.5', '1', 'bottle', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 64),
('Sauces & Condiments', 'Duck Sauce', '2', '4', 'bag', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 65),
('Sauces & Condiments', 'Onion Dressing', '0.5', '1', 'bottle', '1', '2', 'bottle', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 66),
('Sauces & Condiments', 'Garlic Oil', NULL, NULL, 'can', NULL, NULL, NULL, NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 67),
('Sauces & Condiments', 'Cauliflower Sauce', '1', '2', 'bag', '3', '6', 'bag', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 68),
('Sauces & Condiments', 'Okinawa Soju', '1', '1', 'bottle', '1', '2', 'bottle', NULL, NULL, NULL, 'prep/fill/unsure', '', NULL, 69),
('Sauces & Condiments', 'S. Chilli', '1', '1', 'bottle', NULL, NULL, NULL, NULL, NULL, NULL, 'buy/fill/unsure', '', NULL, 70),
('Sauces & Condiments', 'QP Mayo', '1', '2', 'bottle', NULL, NULL, NULL, NULL, NULL, NULL, 'buy/fill/unsure', '', NULL, 71),
('Sauces & Condiments', 'Yuzu Kosho', '1', '2', 'bottle', NULL, NULL, NULL, NULL, NULL, NULL, 'buy/fill/unsure', '', NULL, 72);
